Thing model types
w3c/wot-scripting-api pull request #373
Opened 2022-01-27 15:43 UTC by relu91

As discussed in the previous calls, this PR adds thing models types to our repository. It follows the same logic of the thing-description package with automatic synchronization to [ wot-thing-description](https://github.com/w3c/wot-thing-description).

2022-01-31 11:07 UTC, danielpeintner requested changes
LGTM

Minor:
I suggest to add a link to the main TS readme
https://github.com/w3c/wot-scripting-api/tree/main/typescript

2022-01-31 12:34 UTC, danielpeintner commented on typescript/thing-model/README.md
> +# wot-thing-description-types
name needs to be fixed

2022-01-31 12:36 UTC, danielpeintner approved these changes

2022-01-31 12:37 UTC, danielpeintner commented
Scripting API 2022-01-31

* @relu91 fixes git history. Can be merged after that.

2022-01-31 13:46 UTC, JKRhb approved these changes

2022-01-31 13:53 UTC, relu91 commented
@danielpeintner ready to go (I've just fixed a rebase leftover)

2022-01-31 14:11 UTC, danielpeintner commented
@relu91 my comment about readme was more about the main readme were we currently have 2 items but with this PR it should be 3

![grafik](https://user-images.githubusercontent.com/11281461/151808692-a3e6069f-3909-446a-849e-11304f4ddca0.png)

2022-02-03 09:59 UTC, relu91 commented
@danielpeintner ✅

2022-02-03 10:15 UTC, merged