refactor: move allowed types out of the parenthesis to make it more official
w3c/wot-scripting-api pull request #414
Opened 2022-07-11 15:04 UTC by danielpeintner

fixes https://github.com/w3c/wot-scripting-api/issues/403

***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/414.html" title="Last updated on Jul 18, 2022, 12:23 PM UTC (2f2d1ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/414/cf3d575...danielpeintner:2f2d1ca.html" title="Last updated on Jul 18, 2022, 12:23 PM UTC (2f2d1ca)">Diff</a>

2022-07-13 08:31 UTC, relu91 requested changes
I would use the ref to the definition of the types as shown in the comment below. Moreover, I am ok for using MUST.

2022-07-13 08:31 UTC, relu91 commented on index.html
> +	  The possible values are of type <code>null</code>, <code>boolean</code>, <code>number</code>, <code>string</code>, <code>array</code>, or <code>object</code>.
```suggestion
	  The possible values are of type <a href="https://262.ecma-international.org/11.0/#sec-ecmascript-language-types-null-type">null</a>, <a href="https://262.ecma-international.org/11.0/#sec-ecmascript-language-types-boolean-type">boolean</a>, <a href="https://262.ecma-international.org/11.0/#sec-ecmascript-language-types-number-type">number</a>, <a href="https://262.ecma-international.org/11.0/#sec-ecmascript-language-types-string-type">string</a>, <a href="https://262.ecma-international.org/11.0/#sec-array-objects">array</a>, or <a href="https://262.ecma-international.org/11.0/#sec-object-type">object</a>.
```

2022-07-14 14:56 UTC, danielpeintner commented on index.html
> +	  The possible values are of type <code>null</code>, <code>boolean</code>, <code>number</code>, <code>string</code>, <code>array</code>, or <code>object</code>.
👍

2022-07-15 07:14 UTC, relu91 approved these changes

2022-07-18 11:22 UTC, danielpeintner commented
Call 2022-07-18
* agreed to use MUST
* merge afterwards

2022-07-18 12:24 UTC, merged