Eclipse Thingweb links fixes
w3c/wot-scripting-api pull request #549
Opened 2024-04-27 23:29 UTC by egekorkan

The project has a new GitHub organization now and https webpage instead of http

2024-04-29 08:14 UTC, relu91 approved these changes

2024-04-29 12:49 UTC, danielpeintner requested changes
The changes are fine but I think there is at least one more place which needs adjustments.
see https://github.com/w3c/wot-scripting-api/blob/ab7cd691b25704266334d7eda4cc17e616161960/index.html#L4276

2024-04-29 13:29 UTC, egekorkan commented
> The changes are fine but I think there is at least one more place which needs adjustments. see
> 
> https://github.com/w3c/wot-scripting-api/blob/ab7cd691b25704266334d7eda4cc17e616161960/index.html#L4276

Done as well :)

2024-04-29 14:26 UTC, danielpeintner approved these changes

2024-05-05 17:25 UTC, JKRhb approved these changes

2024-05-13 11:28 UTC, relu91 approved these changes

2024-05-13 11:29 UTC, merged